import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from "vite";

import { editionDev } from "./tsscripts/utils/vite-edition-dev.ts";

// Vite only builds the CSS/JS bundle; the HTML pages are generated by ant/XSLT.
// Run `ant` before `vite build`. The dev server serves html/ with hot reload.
export default defineConfig(({ command }) => ({
	plugins: [tailwindcss(), editionDev()],
	// relative URLs inside the bundle, so it works under any base path
	base: "./",
	// dev: serve the ant output as is; build: nothing to copy
	publicDir: command === "serve" ? "html" : false,
	appType: "mpa",
	server: {
		host: true,
		port: 5173,
		watch: {
			// pages are written by ant; edition-dev reloads once ant is done
			ignored: ["**/.pnpm-store/**", "**/html/**/*.html"],
		},
	},
	// don't crawl the generated pages for dependencies
	optimizeDeps: {
		entries: ["tsscripts/main.ts"],
	},
	build: {
		emptyOutDir: false,
		outDir: "html",
		copyPublicDir: false,
		rolldownOptions: {
			input: ["tsscripts/main.ts", "styles/index.css"],
			output: {
				entryFileNames: "js/[name].js",
				chunkFileNames: "js/[name]-[hash].js",
				assetFileNames: (asset) =>
					asset.names.some((name) => name.endsWith(".css"))
						? "css/[name][extname]"
						: "js/[name]-[hash][extname]",
			},
		},
	},
}));
