// Responsive WebP versions of the images in data/img/, run by build.xml before the pages
// (or by hand: pnpm images).
//
// For every source image it writes html/img/<name>-<width>.webp and lists them in
// html/img/images.xml, which the tei:graphic template in xslt/partials/shared.xsl reads
// to build the <img> srcset, width and height.
// Files newer than their source are kept, so repeated builds only redo what changed.
import { copyFile, mkdir, readdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";

import sharp from "sharp";

const SOURCE_DIR = "data/img";
const OUTPUT_DIR = "html/img";
const MANIFEST = path.join(OUTPUT_DIR, "images.xml");
const SOURCE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp", ".tif", ".tiff"]);
// vector images are copied as they are; the tei:graphic template links them directly
const COPY_EXTENSIONS = new Set([".svg"]);

// target widths in px; widths above the source width are skipped, the source width is always added
const WIDTHS = [640, 1280, 1920];
const WEBP_QUALITY = 78;

interface Variant {
	file: string;
	width: number;
	height: number;
}

async function isUpToDate(output: string, sourceModified: number): Promise<boolean> {
	try {
		return (await stat(output)).mtimeMs >= sourceModified;
	} catch {
		return false;
	}
}

function xmlAttribute(value: string | number): string {
	return String(value).replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;");
}

async function processImage(name: string): Promise<{ entry: string; files: string[] }> {
	const source = path.join(SOURCE_DIR, name);
	const sourceModified = (await stat(source)).mtimeMs;
	const { width, height } = await sharp(source).metadata();
	const base = path.parse(name).name;
	const widths = [...new Set([...WIDTHS.filter((w) => w < width), width])];

	const variants: Variant[] = widths.map((w) => ({
		file: `${base}-${w}.webp`,
		width: w,
		height: Math.round((height * w) / width),
	}));
	// sharp encodes on its own thread pool, so all variants can be requested at once
	const written = await Promise.all(
		variants.map(async ({ file, width: w }) => {
			const output = path.join(OUTPUT_DIR, file);
			if (await isUpToDate(output, sourceModified)) return false;
			await sharp(source).resize({ width: w }).webp({ quality: WEBP_QUALITY }).toFile(output);
			return true;
		}),
	);
	console.log(
		`[images] ${name}: ${variants.length} variants (${written.filter(Boolean).length} written)`,
	);

	const entry = [
		`  <image name="${xmlAttribute(name)}" width="${width}" height="${height}">`,
		...variants.map(
			(v) =>
				`    <variant file="${xmlAttribute(v.file)}" width="${v.width}" height="${v.height}"/>`,
		),
		"  </image>",
	].join("\n");
	return { entry, files: variants.map((v) => v.file) };
}

await mkdir(OUTPUT_DIR, { recursive: true });
const names = (await readdir(SOURCE_DIR)).filter((name) =>
	SOURCE_EXTENSIONS.has(path.extname(name).toLowerCase()),
);
names.sort();

const results = await Promise.all(names.map(processImage));

const copied = (await readdir(SOURCE_DIR)).filter((name) =>
	COPY_EXTENSIONS.has(path.extname(name).toLowerCase()),
);
await Promise.all(
	copied.map(async (name) => {
		const output = path.join(OUTPUT_DIR, name);
		if (await isUpToDate(output, (await stat(path.join(SOURCE_DIR, name))).mtimeMs)) return;
		await copyFile(path.join(SOURCE_DIR, name), output);
		console.log(`[images] ${name}: copied`);
	}),
);

// drop everything in html/img/ that is not a current variant (removed images, old formats)
const keep = new Set([path.basename(MANIFEST), ...results.flatMap((r) => r.files), ...copied]);
const stale = (await readdir(OUTPUT_DIR)).filter((file) => !keep.has(file));
await Promise.all(stale.map((file) => rm(path.join(OUTPUT_DIR, file))));

await writeFile(
	MANIFEST,
	`<?xml version="1.0" encoding="UTF-8"?>\n<!-- generated by tools/images.ts -->\n<images>\n${results.map((r) => r.entry).join("\n")}\n</images>\n`,
);
